//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Net;
using System.Collections;

namespace MoreThanGamers
{
	public class AnonymusScoreService : MTGService
	{
		private MTGSocket socket;
		public Int32 numSuccessSession;
		public AnonymusScoreService (MTGApi api, MTGSocket socket) :base(api,"anonymuschallenge")
		{
			this.socket = socket;
			numSuccessSession = 0;
		}

		protected sealed override IEnumerator callService ()
		{

			TokenService tokenService = new TokenService(this.api,socket.socketId,socket.password);
			
			yield return api.StartCoroutine(tokenService.exectureService());
			
			if(tokenService.isError)
			{
				setError(tokenService.getStatus,tokenService.getErrorMessage);
				yield break;
			}

			WWWForm form2 = new WWWForm();

			form2.AddField("gameId",api.game_id);
			form2.AddField("socketId", socket.socketId);
			form2.AddField("sessionId", api.getSessionCode());
			form2.AddField("token", tokenService.Token);

			WWW w = new WWW(this.connectionUrl,form2);
			
			yield return w; yield return new WaitForSeconds(1f);
			if (!String.IsNullOrEmpty(w.error))
			{
				this.setError(MTGService.EXTERNAL_ERROR,w.error);
				yield break ;
			}
			
			//	input=prueba.Substring(1,prueba.Length-2);
			JSONObject j = new JSONObject(w.text.Trim());
			if(!this.checkstatus(j))
			{
				yield break;
			}
			Debug.Log("print : "+j.GetField("challenge").ToString()+" ");
			numSuccessSession = Int32.Parse( j.GetField("challenge").GetField("count").str);

		}



	}


}

