//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Net;
using System.Collections;

namespace MoreThanGamers
{
	public class GameSessionService : MTGService
	{

		public string sessionCode = "";
		 
		public GameSessionService (MTGApi api) :base(api,"session")
		{

		}

		protected sealed override IEnumerator callService()
		{

		  
			WWWForm form = new WWWForm();
			form.AddField("gameId",  api.GameId);
			form.AddField("secretCode", api.getSecretCode());
			WWW w = new WWW(this.connectionUrl,form);
			
			yield return w; yield return new WaitForSeconds(1f);

			if (!String.IsNullOrEmpty(w.error))
			{
				this.setError(MTGService.EXTERNAL_ERROR,w.error);
					yield break;
			}

			JSONObject j = new JSONObject(w.text.Trim());
			if(!this.checkstatus(j))
				yield break;
			sessionCode = j.GetField("secretCode").str;

		}
	}
}

