//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Net;
using System.Collections;

namespace MoreThanGamers
{
		public class MetricService : MTGService
		{
			
			private int metricId;
			private int metricValue;
			

			public MetricService (MTGApi api,int metricId, int metricValue) : base(api,"metric")
			{
				
				this.metricId = metricId;
				this.metricValue = metricValue;
				
			}

			protected sealed override IEnumerator callService()
			{
				
				string url = this.connectionUrl;
				
				WWWForm form = new WWWForm();
				form.AddField("sessionId",api.getSessionCode());
				form.AddField("secretCode", api.getSecretCode());
				form.AddField("metricId",metricId);
				form.AddField("quantity",metricValue);
				WWW w = new WWW(url,form);
				
				yield return w;
				
				//print("metricaaaaa\n");
				
				// Add a wait to make sure we have the definitions
				
				yield return new WaitForSeconds(1f);
				
				//print("metricaaaaa enviada\n");
				
				// Extract the spheres from our JSON results
				//string encodedString = "{\"field1\": 0.5,\"field2\": \"sampletext\"},\"field3\": [1,2,3]}";
			if (!String.IsNullOrEmpty(w.error))
				{
					this.setError(MTGService.EXTERNAL_ERROR,w.error);
					yield break;
				}
				
				string content = w.text.Trim();

				JSONObject j = new JSONObject(content);
				this.checkstatus(j);
				//No return extra data;
				//PlayerPrefs.SetString("session",secret_code); //??

			}

			
			
		}
}

