//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public class ServiceStatus
	{
		public enum ServiceCode
		{
			NO_VALID_ERROR, 
			CORRECT,
			GAME_ERROR,
			SOCKET_ERROR,
			LOGIN_ERROR,
			PLAYER_ERROR,
			CHALLENGE_ERROR,
			CHALLENGE_NOT_VALID,
			SECURITY_ERROR,
			METRIC_ERROR,
			EMAIL_ERROR ,
			EXTERNAL_RESOURCE_ERROR,
			SECURITY_GAME_SESSION_ERROR,
			NO_PLAYER_LOGED ,
			ANONYMUS_DISABLED
		}
	}
}

		/*public static readonly String[] errorMessages = 
		{
			"Error Code not valid",
			"Correct",
			"Game doesn't exits or is not aviable",
			"Socket doesn't exits or is not aviable",
			"Login failed, maybe email or password",
			"That player doesn't exists or is not aviable",
			"The challenge doesn't exists or si not aviable",
			"The challenge is already finished. OR Challenge state incorrect",
			"Security Error",
			"Error sending the email",
			"Error acceding a external resource. ",
			"Security error when accessing to Game Session Service",
			"The metric doesn't exists in that game",
			"There is no player Logged -- @Deprecated",
			"Anonymus Players are disabled",
		}*/








