//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Net;
using System.Collections;

namespace MoreThanGamers
{
	public class TokenService : MTGService
	{
		private int socketId;
		private string password;
		private string token;
		public string Token { get { return token; }}

		public TokenService (MTGApi api, int socketId, string password) : base(api,"token")
		{
			this.socketId = socketId;
			this.password = password;
			token = null;
		}

		protected sealed override IEnumerator callService()
		{


			WWWForm form = new WWWForm();
			form.AddField("gameId", this.api.GameId);
			form.AddField("socketId", socketId);
			form.AddField("password", password);
			WWW w = new WWW(this.connectionUrl,form);
			
			yield return w;
			yield return new WaitForSeconds(1f); // For make it sure
			//Debug.Log("Token called");
			if (!String.IsNullOrEmpty(w.error))
			{
				this.setError(MTGService.EXTERNAL_ERROR,w.error);
				yield break;
			}
			// Extract the spheres from our JSON results
			//string encodedString = "{\"field1\": 0.5,\"field2\": \"sampletext\"},\"field3\": [1,2,3]}";
			//Debug.Log("Token Recibed");
			JSONObject j = new JSONObject(w.text.Trim());

			if(!this.checkstatus(j))
				yield break;

			token = j.GetField("token").str;
			//Debug.Log("OBtenido token " +token);
			//Debug.Log("Token called "+token);
		}
	}
}