//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections;

namespace MoreThanGamers
{
	public class ConectionErrorMessage : MonoBehaviour
	{
		private static Texture2D _staticRectTexture;
		private static GUIStyle _staticRectStyle;

		public Rect messageRectnagle;
		private MTGApi api;
		private Rect screenRect;
		private Color transparency;
		void Start()
		{
			api = FindObjectOfType<MTGApi>();
			screenRect = new Rect(0,0,Screen.width,Screen.height);
			transparency = Color.white;
			messageRectnagle = new Rect(Screen.width/2-100,Screen.height/2-20,200,40);
			transparency.a = 0.5f;
		}
	


		void OnGUI()
		{
			GUI.color = transparency;
			GUIDrawRect(screenRect,Color.white);
			GUI.color = Color.white;
			if (GUI.Button (messageRectnagle, "Error en la conexion.\nReintentar")  )  {

				api.restartServices();
				this.enabled = false;
			}
		}
		public static void GUIDrawRect( Rect position, Color color )
		{
			if( _staticRectTexture == null )
			{
				_staticRectTexture = new Texture2D( 1, 1 );
			}
			
			if( _staticRectStyle == null )
			{
				_staticRectStyle = new GUIStyle();
			}
			
			_staticRectTexture.SetPixel( 0, 0, color );

			_staticRectTexture.Apply();
			
			_staticRectStyle.normal.background = _staticRectTexture;
			
			GUI.Box( position, GUIContent.none, _staticRectStyle );
			
			
		}
	}
}

