//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections;

namespace MoreThanGamers
{
	public class MTGPlayer
	{
		private int id;
		private string alias;
		private string email;
		private string img_url;

		private MTGApi api;

		public MTGPlayer (MTGApi api, JSONObject jPlayer)
		{
			this.api = api;
			id = int.Parse( jPlayer.GetField("id").str);
			alias = jPlayer.GetField("alias").str;
			email = jPlayer.GetField("email").str;
			img_url = jPlayer.GetField("image_url").str;
		}

		public int ID { get { return id; }}
		public string Alias { get { return alias; }}
		public string Email { get { return email; }}
		public string ImgUrl { get { return img_url; }}
		public MTGApi getMTGApi()
		{
			return api;
		}
	}
}

